permalink: /:year:month:day/:title
url: #Your url here
baseurl: /project

# variables
name: Hub of PIH
description: Your description here
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
mathjax: true
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
